Repository tlsfuzzer/tlslite-ng, pull requests merged in 2018-12, with the labels that each got.

#321 document that all RSA key operations are on bytes
  tlslite/utils/rsakey.py
Labels: maintenance

#323 fix Python 2.6 builds
  build-requirements-2.6.txt
  unit_tests/test_tlslite_utils_deprecations.py
Labels: maintenance

#324 TLS1.3 downgrade sentinel
  scripts/tls.py
  tlslite/constants.py
  tlslite/tlsconnection.py
Labels: bug, enhancement

#326 fix tls.py client compatibility with python 3
  scripts/tls.py
Labels: bug

#332 run simple test for tls.py too
  Makefile
Labels: maintenance

#330 Replaced time.clock() with timeStamp()
  scripts/tls.py
  tlslite/utils/compat.py
Labels: bug

#334 Resumption cipher mismatch
  tests/tlstest.py
  tlslite/tlsconnection.py
Labels: bug
