Repository tlsfuzzer/tlslite-ng, pull requests merged in 2018-04, with the labels that each got.

#238 increase timeout for SRP (db) case
  tests/tlstest.py
Labels: bug, review request

#239 fix API break in certChain property
  tlslite/messages.py
  unit_tests/test_tlslite_messages.py
Labels: bug, review request

#232 fix M2Crypto 0.27.0 test compatibility
  unit_tests/test_tlslite_utils_keyfactory.py
Labels: bug, review request

#244 Move server key exchange sig
  tlslite/tlsconnection.py
Labels: bug

#246 Fix 8192 bit group from RFC 5054
  tlslite/mathtls.py
Labels: bug, review request

#202 3DES implementation
  tlslite/utils/cipherfactory.py
  tlslite/utils/python_tripledes.py
  unit_tests/test_tlslite_recordlayer.py
  unit_tests/test_tlslite_utils_tripledes.py
Labels: enhancement

#248 fix type of raised object
  scripts/tls.py
  scripts/tlsdb.py
Labels: bug
