Repository tlsfuzzer/tlslite-ng, pull requests merged in 2018-06, with the labels that each got.

#263 Cookie extension parser
  tlslite/extensions.py
  tlslite/utils/codec.py
  unit_tests/test_tlslite_extensions.py
  unit_tests/test_tlslite_utils_codec.py
Labels: enhancement

#267 add codeclimate test coverage
  .travis.yml
Labels: maintenance

#269 Coverage fixes
  .travis.yml
  Makefile
  build-requirements.txt
  tests/tlstest.py
Labels: maintenance

#270 Fix issues and more tests in tlsconnection.py
  scripts/tls.py
  tests/tlstest.py
  tlslite/tlsconnection.py
Labels: bug

#271 SSL3 pad size
  scripts/tls.py
  tlslite/recordlayer.py
  tlslite/utils/constanttime.py
Labels: bug

#240 Add OCSP signature verification
  tlslite/ocsp.py
  tlslite/signed.py
  unit_tests/test_tlslite_ocsp.py
  unit_tests/test_tlslite_signed.py
Labels: enhancement

#266 PSK key exchange
  tests/tlstest.py
  tlslite/handshakesettings.py
  tlslite/tlsconnection.py
  unit_tests/test_tlslite_handshakesettings.py
Labels: enhancement

#272 fix PSK identity parsing in tls.py in python3
  scripts/tls.py
Labels: bug

#274 fix FFDHE key exchange in TLS 1.3
  tlslite/keyexchange.py
  unit_tests/test_tlslite_keyexchange.py
Labels: bug

#273 switch to ap traffic keys for server after server Finished
  tlslite/tlsconnection.py
Labels: bug

#276 Send alert for malformed finished
  tlslite/tlsconnection.py
Labels: bug

#281 Test coverage for cryptomath
  tlslite/utils/cryptomath.py
  unit_tests/test_tlslite_utils_cryptomath.py
Labels: maintenance
