Repository tlsfuzzer/tlslite-ng, pull requests merged in 2018-08, with the labels that each got.

#283 make python 3.7 official
  .travis.yml
Labels: maintenance

#298 stylistic fixes around Python_AES class
  pylintrc
  tlslite/utils/deprecations.py
  tlslite/utils/python_aes.py
  tlslite/utils/python_aesgcm.py
  tlslite/utils/rijndael.py
  unit_tests/test_tlslite_utils_aesgcm.py
  unit_tests/test_tlslite_utils_deprecations.py
  unit_tests/test_tlslite_utils_rijndael.py
Labels: maintenance

#304 send alert msg about invalid key_share
  tlslite/tlsconnection.py
Labels: bug

#155 Heartbeat extension
  tests/tlstest.py
  tlslite/constants.py
  tlslite/extensions.py
  tlslite/handshakesettings.py
  tlslite/messages.py
  tlslite/messagesocket.py
  tlslite/tlsconnection.py
  tlslite/tlsrecordlayer.py
  tlslite/utils/format_output.py
  unit_tests/test_tlslite_extensions.py
  unit_tests/test_tlslite_handshakesettings.py
  unit_tests/test_tlslite_messages.py
  unit_tests/test_tlslite_tlsrecordlayer.py
Labels: enhancement
