Repository tlsfuzzer/tlslite-ng, pull requests merged in 2018-09, with the labels that each got.

#312 use pycparser compatible with py2.6
  build-requirements-2.6.txt
Labels: maintenance

#313 allow reading a chain of certificates with -c option
  scripts/tls.py
Labels: bug, enhancement

#310 fix handling of invalid key-share
  tlslite/tlsconnection.py
Labels: bug
