Repository tlsfuzzer/tlslite-ng, pull requests merged in 2019-01, with the labels that each got.

#333 Add support for CertificateRequest (TLS 1.3)
  tests/tlstest.py
  tlslite/constants.py
  tlslite/keyexchange.py
  tlslite/messages.py
  tlslite/tlsconnection.py
  unit_tests/test_tlslite_keyexchange.py
  unit_tests/test_tlslite_messages.py
Labels: enhancement

#336 Fix bug when returning errors for _tryDecrypt
  tlslite/tlsconnection.py
Labels: bug

#337 Fix tests of key type used for verification
  tlslite/tlsconnection.py
  tlslite/utils/keyfactory.py
  tlslite/utils/openssl_rsakey.py
  tlslite/utils/pycrypto_rsakey.py
  tlslite/utils/python_rsakey.py
  tlslite/utils/rsakey.py
  tlslite/x509.py
Labels: bug

#338 Record size limit extension
  tests/tlstest.py
  tlslite/constants.py
  tlslite/extensions.py
  tlslite/handshakesettings.py
  tlslite/messagesocket.py
  tlslite/recordlayer.py
  tlslite/tlsconnection.py
  tlslite/tlsrecordlayer.py
  unit_tests/test_tlslite_extensions.py
  unit_tests/test_tlslite_handshakesettings.py
  unit_tests/test_tlslite_messages.py
  unit_tests/test_tlslite_recordlayer.py
Labels: enhancement

#339 Fix TLS1.3 handshakes to refuse pkcs1 signatures
  tlslite/tlsconnection.py
Labels: bug

#287 Send handshake messages in as few records as possible, send multiple new session tickets
  scripts/tls.py
  tlslite/handshakesettings.py
  tlslite/tlsconnection.py
  tlslite/tlsrecordlayer.py
Labels: enhancement, review request
