Repository tlsfuzzer/tlslite-ng, pull requests merged in 2019-11, with the labels that each got.

#354 add HelloRequest message object
  tlslite/messages.py
  unit_tests/test_tlslite_messages.py
Labels: enhancement

#369 Remove python3.2 from Travis config
  .travis.yml
Labels: maintenance

#196 ECDSA support
  scripts/tls.py
  tests/tlstest.py
  tlslite/handshakesettings.py
  tlslite/tlsconnection.py
  tlslite/x509.py
  tlslite/x509certchain.py
  unit_tests/test_tlslite_handshakesettings.py
  unit_tests/test_tlslite_x509.py
Labels: complex, enhancement

#371 more readable error messages for malformed exceptions
  tlslite/extensions.py
  tlslite/utils/codec.py
  unit_tests/test_tlslite_messages.py
Labels: enhancement

#341 Post handshake KeyUpdate support
  Makefile
  scripts/tls.py
  tests/tlstest.py
  tlslite/constants.py
  tlslite/messages.py
  tlslite/recordlayer.py
  tlslite/tlsrecordlayer.py
  unit_tests/test_tlslite_messages.py
Labels: enhancement

#365 Add support for AES-CCM TLS1.2 and 1.3 ciphers, both with full and tr…
  tests/tlstest.py
  tlslite/constants.py
  tlslite/handshakesettings.py
  tlslite/recordlayer.py
  tlslite/tlsconnection.py
  tlslite/utils/aesccm.py
  tlslite/utils/cipherfactory.py
  tlslite/utils/python_aesccm.py
  unit_tests/test_tlslite_constants.py
  unit_tests/test_tlslite_utils_aesccm.py
Labels: enhancement

#374 Add --cipherslist switch
  scripts/tls.py
Labels: enhancement

#350 Post handshake auth
  scripts/tls.py
  tests/tlstest.py
  tlslite/constants.py
  tlslite/errors.py
  tlslite/tlsconnection.py
  tlslite/tlsrecordlayer.py
Labels: enhancement
